services:
  traefik:
    build: .
    container_name: traefik
    ports:
      - "8081:80"
      - "8082:8080" 
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./traefik.yml:/etc/traefik/traefik.yml"
      - "./dynamic_config.yml:/etc/traefik/dynamic_config.yml"
