http:
  routers:
    experian-router:
      rule: "PathPrefix(`/experian`)"
      service: experian
      entryPoints:
        - web
      middlewares:
        - stripExperianPrefix

    lexis-router:
      rule: "PathPrefix(`/lexis`)"
      service: lexis
      entryPoints:
        - web
      middlewares:
        - stripExperianPrefix

  services:
    experian:
      loadBalancer:
        servers:
          - url: "https://digidates.de/api/v1/checkdate?date=2023-01-01"

    lexis:
      loadBalancer:
        servers:
          - url: "https://dogapi.dog/docs/api-v2"

  middlewares:
    stripExperianPrefix:
      stripPrefix:
        prefixes:
          - "/experian"
    stripLexisPrefix:
      stripPrefix:
        prefixes:
          - "/lexis"
