http:
  routers:
    router-experian:
      rule: "Headers(`X-Target-Endpoint`, `experian`)"
      service: service-experian
      entryPoints:
        - web
      middlewares:
        - experian-headers

    router-lexisnexis:
      rule: "Headers(`X-Target-Endpoint`, `lexisnexis`)"
      service: service-lexisnexis
      entryPoints:
        - web
      middlewares:
        - lexisnexis-headers

  services:
    service-experian:
      loadBalancer:
        servers:
          - url: "http://httpbin.org:80"

    service-lexisnexis:
      loadBalancer:
        servers:
          - url: "https://catfact.ninja:443"

  middlewares:
    experian-headers:
      headers:
        customRequestHeaders:
          Host: "httpbin.org"

    lexisnexis-headers:
      headers:
        customRequestHeaders:
          Host: "catfact.ninja"
