http:
  routers:
    experian-router:
      rule: "PathPrefix(`/experian`)"
      service: experian
      entryPoints:
        - web

    lexis-router:
      rule: "PathPrefix(`/lexis`)"
      service: lexis
      entryPoints:
        - web

  services:
    experian:
      loadBalancer:
        servers:
          - url: "http://httpbin.org:80"

    lexis:
      loadBalancer:
        servers:
          - url: "https://catfact.ninja:443"
