http:
  routers:
    experian-router:
      rule: "PathPrefix(`/experian`)"
      service: experian
      entryPoints:
        - web
      middlewares:
        - replaceExperianPrefix

    lexis-router:
      rule: "PathPrefix(`/lexis`)"
      service: lexis
      entryPoints:
        - web
      middlewares:
        - replaceLexisPrefix

  services:
    experian:
      loadBalancer:
        servers:
          - url: "https://digidates.de"

    lexis:
      loadBalancer:
        servers:
          - url: "https://dogapi.dog"

  middlewares:
    replaceExperianPrefix:
      replacePathRegex:
        regex: "^/experian(.*)"
        replacement: "/api/v1/checkdate?date=2023-01-11"

    replaceLexisPrefix:
      replacePathRegex:
        regex: "^/lexis(.*)"
        replacement: "/api/v2/breeds"
