http:
  routers:
    service1-router:
      rule: "PathPrefix(`/experian`)"
      service: experian
      entryPoints:
        - web

    service2-router:
      rule: "PathPrefix(`/lexis`)"
      service: lexisnexis
      entryPoints:
        - web

  services:
    service1:
      loadBalancer:
        servers:
          - url: "http://httpbin.org:80"

    service2:
      loadBalancer:
        servers:
          - url: "https://catfact.ninja:443"