entryPoints:
  web:
    address: ":80"

api:
  dashboard: true
  insecure: true

providers:
  docker: {}
  file:
    filename: "/etc/traefik/dynamic_config.yml"

log:
  level: TRACE

accessLog:
  filePath: "/var/log/traefik/access.log"
  format: json
